# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pushnotification_pb2 as pushnotification__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendNotification = channel.unary_unary(
        '/pushnotification.Greeter/SendNotification',
        request_serializer=pushnotification__pb2.NotificationRequest.SerializeToString,
        response_deserializer=pushnotification__pb2.NotificationReply.FromString,
        )
    self.NotificationLogs = channel.unary_unary(
        '/pushnotification.Greeter/NotificationLogs',
        request_serializer=pushnotification__pb2.NotificationLogsRequest.SerializeToString,
        response_deserializer=pushnotification__pb2.NotificationLogsReply.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendNotification(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NotificationLogs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendNotification': grpc.unary_unary_rpc_method_handler(
          servicer.SendNotification,
          request_deserializer=pushnotification__pb2.NotificationRequest.FromString,
          response_serializer=pushnotification__pb2.NotificationReply.SerializeToString,
      ),
      'NotificationLogs': grpc.unary_unary_rpc_method_handler(
          servicer.NotificationLogs,
          request_deserializer=pushnotification__pb2.NotificationLogsRequest.FromString,
          response_serializer=pushnotification__pb2.NotificationLogsReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pushnotification.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
