# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pushnotification.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pushnotification.proto',
  package='pushnotification',
  syntax='proto3',
  serialized_options=b'\n!io.grpc.examples.pushnotificationB\025PushNotificationProtoP\001\242\002\003HLW',
  serialized_pb=b'\n\x16pushnotification.proto\x12\x10pushnotification\"(\n\x13NotificationRequest\x12\x11\n\tbody_data\x18\x01 \x01(\t\"$\n\x11NotificationReply\x12\x0f\n\x07message\x18\x01 \x01(\t\",\n\x17NotificationLogsRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\"(\n\x15NotificationLogsReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd5\x01\n\x07Greeter\x12`\n\x10SendNotification\x12%.pushnotification.NotificationRequest\x1a#.pushnotification.NotificationReply\"\x00\x12h\n\x10NotificationLogs\x12).pushnotification.NotificationLogsRequest\x1a\'.pushnotification.NotificationLogsReply\"\x00\x42\x42\n!io.grpc.examples.pushnotificationB\x15PushNotificationProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_NOTIFICATIONREQUEST = _descriptor.Descriptor(
  name='NotificationRequest',
  full_name='pushnotification.NotificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body_data', full_name='pushnotification.NotificationRequest.body_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=84,
)


_NOTIFICATIONREPLY = _descriptor.Descriptor(
  name='NotificationReply',
  full_name='pushnotification.NotificationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pushnotification.NotificationReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=122,
)


_NOTIFICATIONLOGSREQUEST = _descriptor.Descriptor(
  name='NotificationLogsRequest',
  full_name='pushnotification.NotificationLogsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_data', full_name='pushnotification.NotificationLogsRequest.json_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=168,
)


_NOTIFICATIONLOGSREPLY = _descriptor.Descriptor(
  name='NotificationLogsReply',
  full_name='pushnotification.NotificationLogsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pushnotification.NotificationLogsReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=210,
)

DESCRIPTOR.message_types_by_name['NotificationRequest'] = _NOTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['NotificationReply'] = _NOTIFICATIONREPLY
DESCRIPTOR.message_types_by_name['NotificationLogsRequest'] = _NOTIFICATIONLOGSREQUEST
DESCRIPTOR.message_types_by_name['NotificationLogsReply'] = _NOTIFICATIONLOGSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationRequest = _reflection.GeneratedProtocolMessageType('NotificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONREQUEST,
  '__module__' : 'pushnotification_pb2'
  # @@protoc_insertion_point(class_scope:pushnotification.NotificationRequest)
  })
_sym_db.RegisterMessage(NotificationRequest)

NotificationReply = _reflection.GeneratedProtocolMessageType('NotificationReply', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONREPLY,
  '__module__' : 'pushnotification_pb2'
  # @@protoc_insertion_point(class_scope:pushnotification.NotificationReply)
  })
_sym_db.RegisterMessage(NotificationReply)

NotificationLogsRequest = _reflection.GeneratedProtocolMessageType('NotificationLogsRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONLOGSREQUEST,
  '__module__' : 'pushnotification_pb2'
  # @@protoc_insertion_point(class_scope:pushnotification.NotificationLogsRequest)
  })
_sym_db.RegisterMessage(NotificationLogsRequest)

NotificationLogsReply = _reflection.GeneratedProtocolMessageType('NotificationLogsReply', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONLOGSREPLY,
  '__module__' : 'pushnotification_pb2'
  # @@protoc_insertion_point(class_scope:pushnotification.NotificationLogsReply)
  })
_sym_db.RegisterMessage(NotificationLogsReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='pushnotification.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=213,
  serialized_end=426,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendNotification',
    full_name='pushnotification.Greeter.SendNotification',
    index=0,
    containing_service=None,
    input_type=_NOTIFICATIONREQUEST,
    output_type=_NOTIFICATIONREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NotificationLogs',
    full_name='pushnotification.Greeter.NotificationLogs',
    index=1,
    containing_service=None,
    input_type=_NOTIFICATIONLOGSREQUEST,
    output_type=_NOTIFICATIONLOGSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
