# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import session_logs_pb2 as session__logs__pb2


class SessionLogsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSessionLogs = channel.unary_unary(
        '/sessionlogs.SessionLogs/GetSessionLogs',
        request_serializer=session__logs__pb2.SessionLogsRequest.SerializeToString,
        response_deserializer=session__logs__pb2.SessionLogsResponse.FromString,
        )


class SessionLogsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSessionLogs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SessionLogsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSessionLogs': grpc.unary_unary_rpc_method_handler(
          servicer.GetSessionLogs,
          request_deserializer=session__logs__pb2.SessionLogsRequest.FromString,
          response_serializer=session__logs__pb2.SessionLogsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sessionlogs.SessionLogs', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
