# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session_logs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='session_logs.proto',
  package='sessionlogs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12session_logs.proto\x12\x0bsessionlogs\"\'\n\x12SessionLogsRequest\x12\x11\n\tbody_data\x18\x01 \x01(\t\"9\n\x13SessionLogsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t2d\n\x0bSessionLogs\x12U\n\x0eGetSessionLogs\x12\x1f.sessionlogs.SessionLogsRequest\x1a .sessionlogs.SessionLogsResponse\"\x00\x62\x06proto3')
)




_SESSIONLOGSREQUEST = _descriptor.Descriptor(
  name='SessionLogsRequest',
  full_name='sessionlogs.SessionLogsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body_data', full_name='sessionlogs.SessionLogsRequest.body_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=74,
)


_SESSIONLOGSRESPONSE = _descriptor.Descriptor(
  name='SessionLogsResponse',
  full_name='sessionlogs.SessionLogsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='sessionlogs.SessionLogsResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='sessionlogs.SessionLogsResponse.sessionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['SessionLogsRequest'] = _SESSIONLOGSREQUEST
DESCRIPTOR.message_types_by_name['SessionLogsResponse'] = _SESSIONLOGSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SessionLogsRequest = _reflection.GeneratedProtocolMessageType('SessionLogsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONLOGSREQUEST,
  '__module__' : 'session_logs_pb2'
  # @@protoc_insertion_point(class_scope:sessionlogs.SessionLogsRequest)
  })
_sym_db.RegisterMessage(SessionLogsRequest)

SessionLogsResponse = _reflection.GeneratedProtocolMessageType('SessionLogsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONLOGSRESPONSE,
  '__module__' : 'session_logs_pb2'
  # @@protoc_insertion_point(class_scope:sessionlogs.SessionLogsResponse)
  })
_sym_db.RegisterMessage(SessionLogsResponse)



_SESSIONLOGS = _descriptor.ServiceDescriptor(
  name='SessionLogs',
  full_name='sessionlogs.SessionLogs',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=235,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSessionLogs',
    full_name='sessionlogs.SessionLogs.GetSessionLogs',
    index=0,
    containing_service=None,
    input_type=_SESSIONLOGSREQUEST,
    output_type=_SESSIONLOGSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SESSIONLOGS)

DESCRIPTOR.services_by_name['SessionLogs'] = _SESSIONLOGS

# @@protoc_insertion_point(module_scope)
